# Copyright 2021 CMakePP
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
name: Tag and Release

on:
  push:
    branches:
      - main

jobs:
  tag:
    uses: ./.github/workflows/tag_tmpl.yaml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
  release:
    runs-on: ubuntu-latest
    needs: tag
    if: | 
      (needs.tag.outputs.bumped_major == 'true') || 
      (needs.tag.outputs.bumped_minor == 'true')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install build package
        run: python -m pip install build --user
      - name: Build binary wheel and source tarball
        run: python -m build --sdist --wheel --outdir dist/
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/

